// SRB/Kerri/Vue/Kerri_Vue_v1.0.0/Kerri/Dark/src/components/Service.vue
<script>
import AOS from 'aos';
import 'aos/dist/aos.css';

export default {
    name: "SERVICE",
    mounted() {
        AOS.init({
            easing: 'ease-in-out-sine',
            duration: 1000
        }); // Initialize AOS
    }
}
</script>

<template>
    <section class="section bg-light" id="services">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="text-center" data-aos="fade-up">
                        <h2>Our <span class="fw-bold">Services</span></h2>
                        <p class="text-muted mx-auto section-subtitle mt-3">It is a long established fact that a reader will
                            be of a page when established fact looking at its layout.</p>
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-growing-chart text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Graphic Design</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-hot-cup text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Unlimited Color</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-upload text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Media Marketing</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-layers text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Unlimited Wifi</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-website-theme text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Responsive Design</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="text-center services-boxes rounded p-4 mt-4" data-aos="fade-up">
                        <div class="services-boxes-icon">
                            <i class="mbri-edit text-custom display-4"></i>
                        </div>
                        <div class="mt-4">
                            <h5 class="mb-0">Easy to customize</h5>
                            <div class="services-title-border"></div>
                            <p class="text-muted mt-3">There are many variations of passages of but the majority have
                                suffered alteration in some form.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-center">
                        <h2 class="fw-bold">I Am Available For Freelancer.</h2>
                    </div>
                    <div class="text-center mt-4">
                        <a href="javascript:void(0)" class="btn btn-custom">Hire Me!</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

// SRB/Busion/React/Busion  React_v1.0.0/src/Components/helperComponents/Services/Service.jsx
import React from "react";
import { Col, Container, Row } from "react-bootstrap";
import Servicebox from "./Service_box";
import { Database } from "react-bootstrap-icons";
import {
  AppRegistrationOutlined,
  CloudUploadOutlined,
  FormatColorFillOutlined,
  LayersOutlined,
  SpaOutlined,
  WifiFindOutlined,
} from "@mui/icons-material";

function Service() {
  const Services = [
    {
      Logo: <Database sx={{ fontSize: 40 }} />,
      Heding: "Graphic Design",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
    {
      Logo: <FormatColorFillOutlined sx={{ fontSize: 40 }} />,
      Heding: "Unlimited Color",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
    {
      Logo: <CloudUploadOutlined sx={{ fontSize: 40 }} />,
      Heding: "Media Marketing",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
    {
      Logo: <WifiFindOutlined sx={{ fontSize: 40 }} />,
      Heding: "Unlimited Wifi",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
    {
      Logo: <SpaOutlined sx={{ fontSize: 40 }} />,
      Heding: "Responsive Design",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
    {
      Logo: <AppRegistrationOutlined sx={{ fontSize: 40 }} />,
      Heding: "Easy to customize",
      Detail:
        "The standard chunk of Lorem Ipsum used since the is reproduced below for those interested.",
    },
  ];
  
  return (
    <React.Fragment>
      {/* START SERVICES  */}
      <section className="section bg-light" id="services">
        <Container>
          <Row className="justify-content-center">
            <Col>
              <div className="text-center mx-auto lan_sec-title">
                <h2 className="fw-bold">Our Services</h2>
                <div className="bus_lan_titbor">
                  <i className="mdi mdi-vector-combine">
                    <LayersOutlined />
                  </i>
                </div>
                <p className="text-muted bus_subtitle mx-auto mt-2">
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
              </div>
            </Col>
          </Row>
          <Row className=" mt-4 pt-4">
            <Servicebox data={Services} />
          </Row>
        </Container>
      </section>
      {/* END SERVICES */}
    </React.Fragment>
  );
}

export default Service;
