// SRB/Kerri/Vue/Kerri_Vue_v1.0.0/Kerri/Light/src/components/Navbar.vue
<script>
export default {
    name: "NAVBAR",
    data() {
        return {
            isNavSticky: false,
            sections: ['home', 'about', 'services', 'client', 'portfolio', 'blog', 'contact'],
            activeSection: "home"
        };
    },
    mounted() {
        window.addEventListener('scroll', this.onWindowScroll);
        window.addEventListener('scroll', this.setActiveSection);
    },
    methods: {
        onWindowScroll() {
            if (
                document.body.scrollTop > 50 ||
                document.documentElement.scrollTop > 50
            ) {
                this.isNavSticky = true;
            } else {
                this.isNavSticky = false;
            }
        },
        /**
         * Toggle menu
         */
        toggleMenu() {
            document.getElementById("navbarNav").classList.toggle("show");
        },
        setActiveSection() {
            const scrollY = window.scrollY;

            for (let i = this.sections.length - 1; i >= 0; i--) {
                const section = this.sections[i];
                const el = document.getElementById(section);
                if (el.offsetTop <= scrollY + 100) {
                    this.activeSection = section;
                    return;
                }
            }
        }
    },
    unmounted() {
        window.removeEventListener('scroll', this.onWindowScroll);
        window.removeEventListener('scroll', this.setActiveSection);
    },
}
</script>

<template>
    <BNav class="navbar navbar-expand-lg custom-nav fixed-top sticky" id="navbar" :class="{ 'stickyadd': isNavSticky }">
        <div class="container">
            <a class="navbar-brand pt-0 logo" href="#">
                <img src="@/assets/images/logo.png" alt="" class="img-fluid logo-light">
                <img src="@/assets/images/logo-dark.png" alt="" class="img-fluid logo-dark">
            </a>
            <button @click="toggleMenu" class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="mdi mdi-menu"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto" id="main_nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#home" :class="{ 'active': activeSection == 'home' }">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about" :class="{ 'active': activeSection == 'about' }">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#services" :class="{ 'active': activeSection == 'services' }">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#client" :class="{ 'active': activeSection == 'client' }">Client</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#portfolio"
                            :class="{ 'active': activeSection == 'portfolio' }">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#blog" :class="{ 'active': activeSection == 'blog' }">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact" :class="{ 'active': activeSection == 'contact' }">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </BNav>
</template>

// SRB/Kerri/REACT/Kerri_React_v1.0.0/Dark/src/components/helperComponents/Navbar.jsx
import React, { useEffect } from "react";

function Navbar() {
  useEffect(() => {
    const handleScroll = () => {
      const navbar = document.querySelector("nav");
      if (navbar) {
        if (window.pageYOffset > 20) {
          navbar.classList.add("stickyadd");
        } else {
          navbar.classList.remove("stickyadd");
        }
      }
    };

    const handleLinkClick = () => {
      const navbarToggler = document.querySelector(".navbar-toggler");
      if (navbarToggler) {
        navbarToggler.click();
      }
    };

    const sections = document.querySelectorAll("section"); 
    const navLinks = document.querySelectorAll(
      "ul.navbar-nav li.nav-item a.nav-link"
    );

    const observerOptions = {
      root: null,
      rootMargin: "0px",
      threshold: 0.7,
    };

    const sectionObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          const sectionId = entry.target.getAttribute("id");
          navLinks.forEach((navLink) => {
            navLink.classList.remove("active");
            if (navLink.getAttribute("href") === `#${sectionId}`) {
              navLink.classList.add("active");
            }
          });
        }
      });
    }, observerOptions);

    sections.forEach((section) => {
      sectionObserver.observe(section);
    });

    window.addEventListener("scroll", handleScroll);

    
    return () => {
      navLinks.forEach((link) => {
        link.removeEventListener("click", handleLinkClick);
      });
      window.removeEventListener("scroll", handleScroll);
      sectionObserver.disconnect();
    };
  }, []);

  return (
    <>
      <nav className="navbar navbar-expand-lg custom-nav navbar-light fixed-top sticky">
        <div className="container">
          <a className="navbar-brand pt-0 logo" href="#">
            <img
              src="assets/images/logo.png"
              alt=""
              className="img-fluid logo-light"
            />
            <img
              src="assets/images/logo-dark.png"
              alt=""
              className="img-fluid logo-dark"
            />
          </a>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="mdi mdi-menu"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ms-auto" id="main_nav">
              <li className="nav-item">
                <a className="nav-link" href="#home">
                  Home
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#about">
                  About
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#services">
                  Services
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#client">
                  Client
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#portfolio">
                  Portfolio
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#blog">
                  Blog
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#contact">
                  Contact
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {/* End Navbar*/}
    </>
  );
}

export default Navbar;
