// SRB/Kerri/REACT/Kerri_React_v1.0.0/Light/src/components/helperComponents/Footer.jsx
import React from "react";

function Footer() {
  return (
    <>
      {/* START FOOTER */}
      <footer className="footer bg-light">
        <div className="container">
          <div className="row justify-content-center text-center">
            <div className="col-md-12">
              <div className="text-center text-white footer-alt">
                <ul className="list-unstyled list-inline mb-0">
                  <li className="list-inline-item">
                   <a href="/#"  onClick={(e) => e.preventDefault()}>
                      <i className="mdi mdi-facebook"></i>
                    </a>
                  </li>
                  <li className="list-inline-item">
                   <a href="/#"  onClick={(e) => e.preventDefault()}>
                      <i className="mdi mdi-linkedin"></i>
                    </a>
                  </li>
                  <li className="list-inline-item">
                   <a href="/#"  onClick={(e) => e.preventDefault()}>
                      <i className="mdi mdi-pinterest"></i>
                    </a>
                  </li>
                  <li className="list-inline-item">
                   <a href="/#"  onClick={(e) => e.preventDefault()}>
                      <i className="mdi mdi-twitter"></i>
                    </a>
                  </li>
                </ul>
                <p className="copyright_content mb-0 mt-3">
                  {new Date().getFullYear()} &copy; Kerri. Design by{" "}
                  <a
                    className="copyright_content"
                    target="_blank" rel="noreferrer"
                    href="https://themeforest.net/user/srbthemes"
                  >
                    SRBThemes.
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      {/* END FOOTER */}
    </>
  );
}

export default Footer;

// SRB/Kerri/Vue/Kerri_Vue_v1.0.0/Kerri/Dark/src/components/Footer.vue
<script>
export default {
    name: "FOOTER",
    Method: {
        topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        },
    },
    mounted() {

        let backtoTop = document.getElementById("back-to-top");

        if (backtoTop) {
            backtoTop = document.getElementById("back-to-top");
            window.onscroll = function () {
                if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                    backtoTop.style.display = "block";
                } else {
                    backtoTop.style.display = "none";
                }
            };
        }
    }
}
</script>

<template>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-md-12">
                    <div class="text-center text-white footer-alt">
                        <ul class="list-unstyled list-inline mb-0">
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-facebook"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-linkedin"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-pinterest"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-twitter"></i></a>
                            </li>
                        </ul>
                        <p class="copyright_content mb-0 mt-3">
                            {{ new Date().getFullYear() }} &copy; kerri. Design by
                            <a class="copyright_content" target="_blank"
                                href="https://themeforest.net/user/SRBThemes">SRBThemes.</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <a href="#" class="back_top" variant="danger" @click="topFunction" id="back-to-top"> <i class="mdi mdi-chevron-up"> </i>
    </a>
</template>
