// SRB/Busion/React/Busion  React_v1.0.0/src/Components/Pages/Index10.jsx
import React, { useState } from "react";
import Button from "react-bootstrap/Button";
import { Link } from "react-router-dom";
import ReactTextRotator from "react-text-rotator";
import bg from "../../assets/Image/home-bg.jpg";
import { Col, Container, Row } from "react-bootstrap";
import Modalvideo from "../helperComponents/Modalvideo";

function Index10() {

  const [isOpen, setOpen] = useState(false);

  const content = [
    {
      text: "We Are Creative Landing Page Template",
      className: "classA",
      animation: "fade",
    },
    {
      text: "Professional Landing Page Template",
      className: "classB",
      animation: "fade",
    },
    {
      text: "We Are Creative And Modern Design",
      className: "classC",
      animation: "fade",
    },
  ];

  return (

    <React.Fragment>

      {/* START HOME */}

      <section
        className=" home-half h-100vh position-relative d-flex align-items-center home-bg-img"
        id="home"
        style={{
          backgroundImage: `url(${bg})`,
          backgroundPosition: "center center",
        }}
      >
        <div className="bg-overlay"></div>
        <Container className=" z-index">
          <Modalvideo modal={isOpen} setOpen={setOpen} />

          <Row className=" justify-content-center">
            <Col>
              <div className="text-white text-center">
                <h1 className="bus_home_title mx-auto">
                  <ReactTextRotator
                    content={content}
                    time={3000}
                    startDelay={0}
                  />
                </h1>
                <p className="bus_home_subtitle pt-4 mx-auto">
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout
                  look like readable English.
                </p>
                <div className="bus_home_btn">
                  <Link to="/#" className="">
                    <Button
                      variant="primary"
                      className="py-2 px-4 fs-6 rounded-5 mt-4 me-3"
                    >
                      Learn More
                    </Button>
                  </Link>
                  <span className="me-3">OR</span>

                 <Link  className="">
                  
                  <Button
                    variant="outline-light"
                    className="py-2 px-4 fs-6 rounded-5 mt-4 me-3"
                    onClick={() => setOpen(true)}
                  >
                    Watch Video
                  </Button>
                </Link>
                 
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      {/* END HOME */}
      
    </React.Fragment>
  );
}

export default Index10;

// SRB/Kerri/Vue/Kerri_Vue_v1.0.0/Kerri/Dark/src/views/index10.vue
<script>
import Layout from "@/layout/index.vue"
export default {
    name: "INDEX10",
    components: {
        Layout
    }
}
</script>

<template>
    <Layout>
        <section class="section h-100vh align-items-center jarallax d-flex" data-jarallax='{"speed": 0.2}'
            style="background-image: url('assets/images/header-bg.jpg');" id="home">
            <div class="bg-overlay"></div>
            <div class="container z-index">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="text-center header-content mx-auto">
                            <h4 class="text-white first-title mb-4">Welcome</h4>
                            <h1 class="header-name text-white text-capitalize mb-0">I'M <span
                                    class="element fw-bold d-none d-sm-inline-block">
                                    <VueWriter :speed="2000"
                                        :array="['Kerri Deo.', 'A Graphic Designer.', 'A Photographer.']" />
                                </span>
                            </h1>
                            <p class="text-white mx-auto header-desc mt-4">It is a long established fact that a reader will
                                be of a page when established fact looking at its layout.</p>
                            <div class="mt-4 pt-2">
                                <a href="javascript:void(0)" class="btn btn-outline-custom btn-round">Download Cv</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="scroll_down">
                <a href="#about" class="scroll">
                    <i class="text-white"></i>
                </a>
            </div>
        </section>
    </Layout>
</template>
