// ThemesBoss/Landik/React/Landik_react_v1.0.0/src/components/Footer.jsx
import React from "react";

function Footer() {
  return (
    <>
      {/* Start Footer  */}
      <footer className="footer_fir">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className="foot_logo mt-3">
                <a href="index_1.html">
                  <img
                    src="assets/images/logo-light.png"
                    alt=""
                    className="img-fluid d-block text-md-center text-sm-center"
                  />
                </a>
              </div>
            </div>
            <div className="col-lg-6">
              <div className="subcribe_foot mt-3">
                <form className="position-relative">
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    required
                  />
                  <button
                    type="submit"
                    className="btn btn-custom"
                    id="subscribe"
                  >
                    Subcribe
                  </button>
                </form>
              </div>
            </div>
          </div>
          <div className="foot_divider mt-5"></div>
          <div className="row mt-3 align-items-center">
            <div className="col-lg-6">
              <div className="footer_menu mt-4">
                <ul className="mb-0 list-inline">
                  <li className="list-inline-item me-0">
                    <a href="javascript:void(0)">Demo</a>
                  </li>
                  <li className="list-inline-item me-0">
                    <a href="javascript:void(0)">Pages</a>
                  </li>
                  <li className="list-inline-item me-0">
                    <a href="javascript:void(0)">Support</a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="col-lg-6">
              <div className="text-lg-end">
                <ul className="list-inline mb-0 fot_social mt-4">
                  <li className="list-inline-item">
                    <a href="javascript:void(0)" className="social-icon">
                      <i className="mdi mdi-facebook"></i>
                    </a>
                  </li>
                  <li className="list-inline-item">
                    <a href="javascript:void(0)" className="social-icon">
                      <i className="mdi mdi-twitter"></i>
                    </a>
                  </li>
                  <li className="list-inline-item">
                    <a href="javascript:void(0)" className="social-icon">
                      <i className="mdi mdi-reddit"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className="row mt-3">
            <div className="col-lg-12">
              <div className="text_copyright text-center mt-3">
                <p className="mb-0">
                  &copy;{" "}
                  {new Date().getFullYear()} {" "}
                  Landik. Design and coded by{" " }
                  <a
                    href="https://themeforest.net/user/themesboss"
                    target="_blank"
                    className="text-white"
                  >
                    ThemesBoss.
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      {/*  End Footer  */}
    </>
  );
}

export default Footer;

// SRB/Kerri/Vue/Kerri_Vue_v1.0.0/Kerri/Light/src/components/Footer.vue
<script>
export default {
    name: "FOOTER",
    Method: {
        topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        },
    },
    mounted() {

        let backtoTop = document.getElementById("back-to-top");

        if (backtoTop) {
            backtoTop = document.getElementById("back-to-top");
            window.onscroll = function () {
                if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                    backtoTop.style.display = "block";
                } else {
                    backtoTop.style.display = "none";
                }
            };
        }
    }

}
</script>

<template>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-md-12">
                    <div class="text-center text-white footer-alt">
                        <ul class="list-unstyled list-inline mb-0">
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-facebook"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-linkedin"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-pinterest"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="javascript:void(0)"><i class="mdi mdi-twitter"></i></a>
                            </li>
                        </ul>
                        <p class="copyright_content mb-0 mt-3">
                            {{ new Date().getFullYear() }} &copy; SRBThemes. Design by
                            <a class="copyright_content" target="_blank" href="https://themeforest.net/user/SRBThemes">
                                SRBThemes.
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <a href="#" class="back_top" variant="danger" @click="topFunction" id="back-to-top"> <i class="mdi mdi-chevron-up"> </i>
    </a>
</template>
